# Generated by Django 2.2.8 on 2019-12-16 18:08

import car_reservation.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_reservation', '0002_auto_20191207_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrentalactive',
            name='end_date',
            field=models.DateTimeField(default=car_reservation.models.in_three_days),
        ),
        migrations.AlterField(
            model_name='carreservation',
            name='purpose',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='carreservation',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
