# Generated by Django 2.2.8 on 2019-12-23 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_reservation', '0003_auto_20191216_1908'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarRentalActive',
        ),
    ]
