export const GET_RESERVATIONS = "GET_RESERVATIONS";
export const DELETE_RESERVATIONS = "DELETE_RESERVATIONS";
export const ADD_RESERVATIONS = "ADD_RESERVATIONS";
export const ADD_RENTAL = "ADD_RENTAL";
