export const GET_RESERVATIONS = "GET_RESERVATIONS";
export const RENT_RESERVATIONS = "RENT_RESERVATIONS";
export const DELETE_RESERVATIONS = "DELETE_RESERVATIONS";
export const ADD_RESERVATIONS = "ADD_RESERVATIONS";
export const GET_RENTALS = "GET_RENTALS";
