export const GET_RESERVATIONS = "GET_RESERVATIONS";
export const DELETE_RESERVATIONS = "DELETE_RESERVATIONS";
export const ADD_RESERVATIONS = "ADD_RESERVATIONS";
export const ADD_RENTAL = "ADD_RENTAL";
export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "GET_MESSAGE";
